apiVersion: v1
kind: Service
metadata:
  name: go-web-service
spec:
  selector:
      app: go-web
  ports:
    - name: http
      port: 31080
      protocol: TCP
      targetPort: 31080
      nodePort: 31080
  type: NodePort